# Generated by Django 6.0 on 2025-12-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenpad', '0004_alter_entry_options_book_slug_entry_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='book_description',
        ),
    ]
