# Generated by Django 6.0 on 2025-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenpad', '0007_remove_genre_slug_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
