# Generated by Django 6.0 on 2025-12-31 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenpad', '0008_remove_entry_id_entry_entry_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='footprints',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='EntryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='screenpad.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
