# Generated by Django 6.0 on 2025-12-31 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenpad', '0009_entry_footprints_entry_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visited_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
