# Generated by Django 6.0 on 2026-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenpad', '0011_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='book_covers/default_cover.png', null=True, upload_to='book_covers/'),
        ),
    ]
